config/routes.rb
Rails.application.routes.draw do

  require "sidekiq/web"
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users
  root to: "pages#home"
  get '/privacy', to: 'pages#privacy_statement', as: 'privacy_statement'
  get '/profile', to: 'users#profile', as: 'profile'
  get '/home', to: 'users#home', as: 'afterloginhp'
  get '/my_profile', to: 'users#my_profile', as: 'my_profile'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get 'usergalleries/ranking', to: 'usergalleries#ranking', as: 'ranking'
  post 'usergalleries/share', to: 'usergalleries#share'
  post 'usergallerycards/delete', to: 'usergallerycards#destroy', as: 'delete'
  get 'usercards/bonus/:usercard_id', to: 'usercards#bonuscard', as: 'usercards_bonus'
  # get 'usercards/detail', to: 'usercards#detail', as: 'usercards_detail'
  get 'usercards/detail/:usercard_id', to: 'usercards#detail', as: 'usercards_detail'
  get 'newcards', to: 'users#new_card', as: 'new_card'

  resources :usercards, only: [:index]
  resources :usergalleries, only: [:index, :create, :show] do
    resources :usergallerycards, only: [:new, :create]
  end

  resources :usersupports, only: [:create]

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_logo.html.erb
<%= link_to root_path, class: "navbar-logo" do %>
        <%= image_tag "logo/astro-card-white.png" %>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-dark navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "/assets/Logo/astro-card-white.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
        <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar", alt: "dropdown menu" %>
          </a>
          <li class="nav-item dropdown">
              <%= link_to "Profile", "#", class: "dropdown-item" %>
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>

  </div>
</div>

<div class="bottom-navbar">
  <div class="bottom-navbar-border">
    <a href="inbox.html"><i class="fa-solid fa-inbox" style="color: #ffffff;"></i></a>
    <a href="home.html"><i class="fa-solid fa-house" style="color: #fafafa;"></i></a>
    <a href="certificate.html"><i class="fa-solid fa-certificate" style="color: #fafafa;"></i></a>
    <a href="meteor.html"><i class="fa-solid fa-meteor" style="color: #fafafa;"></i></a>
  </div>
</div>

app/views/shared/_newnavbar.html.erb
<nav class="top-right" style="z-index:65656565;">
  <% if user_signed_in? %>
    <%= link_to destroy_user_session_path, data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: 'disc l1' do %>
      <div>Log out</div>
    <% end %>
    <%= link_to ranking_path, class: 'disc l2' do %>
      <div>Gallery Ranking</div>
    <% end %>
    <%= link_to usergalleries_path, class: 'disc l3' do %>
      <div>My Gallery</div>
    <% end %>
    <%= link_to usercards_path, class: 'disc l4' do %>
      <div>My Collection</div>
    <% end %>
    <%= link_to profile_path, class: 'disc l5' do %>
      <div>Profile</div>
    <% end %>
    <% if current_user.avatar.attached? %>
      <%= cl_image_tag current_user.avatar.key, class: 'disc l6 toggle' %>
    <% else %>
      <%= image_tag "objects/unknow card.png", alt:'Profile Picture', class: 'disc l6 toggle' %>
    <% end %>

  <% else %>
    <%= link_to "Start?", new_user_session_path, class: 'disc l6 gologin' %>
  <% end %>
</nav>

<script>
  toggle = document.querySelectorAll(".toggle")[0];
  nav = document.querySelectorAll("nav")[0];
  toggle_open_text = 'Menu';
  toggle_close_text = 'Close';

  toggle.addEventListener('click', function() {
    nav.classList.toggle('open');

    if (nav.classList.contains('open')) {
      toggle.innerHTML = toggle_close_text;
    } else {
      toggle.innerHTML = toggle_open_text;
    }
  }, false);

  document.addEventListener("DOMContentLoaded", function() {
    const menu = document.getElementById("menu");
    const openMenu = document.getElementById("open-menu");
    const closeMenu = menu.querySelector(".menu-button.icon-minus");

    openMenu.addEventListener("click", function() {
        menu.classList.add("open");
    });

    closeMenu.addEventListener("click", function() {
        menu.classList.remove("open");
    });
});
</script>