config/routes.rb
Rails.application.routes.draw do

  require "sidekiq/web"
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users
  root to: "pages#home"
  get '/privacy', to: 'pages#privacy_statement', as: 'privacy_statement'
  get '/profile', to: 'users#profile', as: 'profile'
  get '/home', to: 'users#home', as: 'afterloginhp'
  get '/my_profile', to: 'users#my_profile', as: 'my_profile'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get 'usergalleries/ranking', to: 'usergalleries#ranking', as: 'ranking'
  post 'usergalleries/share', to: 'usergalleries#share'
  post 'usergallerycards/delete', to: 'usergallerycards#destroy', as: 'delete'
  get 'usercards/bonus/:usercard_id', to: 'usercards#bonuscard', as: 'usercards_bonus'
  # get 'usercards/detail', to: 'usercards#detail', as: 'usercards_detail'
  get 'usercards/detail/:usercard_id', to: 'usercards#detail', as: 'usercards_detail'
  get 'newcards', to: 'users#new_card', as: 'new_card'

  resources :usercards, only: [:index]
  resources :usergalleries, only: [:index, :create, :show] do
    resources :usergallerycards, only: [:new, :create]
  end

  resources :usersupports, only: [:create]

end

app/models/usercard.rb
class Usercard < ApplicationRecord
  belongs_to :card
  belongs_to :user
  # has_many :cards

  after_commit :detect_bonus_cards, on: [:create]

  private

  def detect_bonus_cards
    @specials = Special.all
    @usercards = Usercard.where(user_id: user_id)

    # create a table with all card id owned by the user, from usercard
    @usercards_tab = []
    @usercards.each do |usercard|
      @usercards_tab << usercard.card.id
    end

    # loop on all the bonus cards
    @specials.each do |specialcard|
      special_tab = specialcard.card_ids.split("-").map(&:to_i)

      result = special_tab.all? { |id| @usercards_tab.include?(id) }
      if result
        # check if the bonus card already exists
        card = Card.where(object_id: specialcard.id, object_type: "Special")
        unless @usercards_tab.include?(card[0].id)
          # give the user a new bonus card
          new_usercard = Usercard.new(user_id: user_id, card_id: card[0].id, seen: false)
          new_usercard.save
        end
      end
    end
  end
end

app/controllers/usercards_controller.rb
class UsercardsController < ApplicationController
  def index
    @usergallery = Usergallerie.where(user: current_user).first
    @usercards = Usercard.where(user: current_user)

    # missing cards
    usercard_ids = @usercards.pluck(:card_id)
    @missingcards = Card.where.not(object_type: "Special").where.not(id: usercard_ids)
  end

  def detail
    @usergallery = Usergallerie.where(user: current_user).first
    @card = Usercard.find(params[:usercard_id])
  end

  def bonuscard
    # @card = Usercard.where(user: current_user).first
    @usergallery = Usergallerie.where(user: current_user).first
    @card = Usercard.find(params[:usercard_id])
    @cardcard = Card.find(@card.card_id)
    @bonuscard = Special.find(@cardcard.object_id)

    @cards_in_bonus = @bonuscard.card_ids.split("-").map(&:to_i)
  end
end

app/views/usercards/bonuscard.html.erb
<div class="display-cards-bg-bc">
  <%= render "shared/newnavbar" %>
  <%= render "shared/logo" %>
  <div class="flip-container">
    <div class="flipper">
      <% card = Card.find(@card.card_id) %>
      <% object = card.object %>
      <!-- Card front -->
      <div class="flip-bcard-front">
        <div class="display-cards-card-bc container">
          <div class="row">
              <p class="display-bonuscards-title bonus-card-title">
                <i class="fas fa-star bonus-card-title"></i><span class="bonus-card-name"><%= object.name_en %></span><i class="fas fa-star bonus-card-title"></i>
              </p>
              <%# <div class="col-md-6 d-flex align-items-center justify-content-center"> %>
                <div class="d-flex flex-column align-items-center justify-content-center">
                  <div class="display-cards-pic">
                    <%= image_tag "objects/#{object.image_path}" %>
                  </div>
                  <div class="display-bcards-info">
                    <div class="horizontal-line"></div>
                    <div class="bonus-front-content">
                      <div>
                        <p style="text-align: left; font-size: 14px; font-family: AKONY;">Family Members</p>
                        <% @cards_in_bonus.each do |id| %>
                          <% card = Card.find(id) %>
                          <% objectolivier = card.object %>
                          <div class="family-member">
                              <div><%= image_tag "objects/#{objectolivier.image_path}"%></div>
                              <div><span class="object-name"><%= objectolivier.name_en.capitalize %></span></div>
                              <div class="object-type"><%= "(#{card.object_type})" %></div>
                          </div>
                        <% end %>
                      </div>
                      <div class="horizontal-line"></div>
                      <div style="text-align: left; font-size: 14px;">
                        <p>Moon Count:<%= object.moon_count %></p>
                        <p>First Discoveries:</p>
                        <p><%= object.first_discoveries %></P>
                        <p>Featured Moons:</p>
                        <p><%= object.featured_moons %></p>
                      </div>
                    </div>
                    <div class="horizontal-line"></div>
                  </div>
                  <div class="display-cards-buttons">
                    <div>
                      <button class="btn flip-button" data-controller="flipcard" data-action="click->flipcard#flip">
                        <i class="fas fa-sync-alt"></i> Flip card
                      </button>
                    </div>
                    <div>
                      <%= simple_form_for(@card, url: usergallery_usergallerycards_path(@usergallery), method: 'POST') do |f| %>
                        <%= f.input :id, as: :hidden %>
                        <%= f.submit "+ Add to gallery", class: 'mb-3 btn' %>
                      <% end %>
                    </div>
                  </div>
                </div>
            <%# </div> %>
          </div>
        </div>
      </div>

      <!-- Card back -->
      <div class="flip-bcard-back">
        <div class="display-cards-card-bc container">
          <div class="row">
            <div class="col-md-6 d-flex align-items-center justify-content-center">
              <p class="display-bonuscards-title"><%= object.name_en %></p>
            </div>
            <div class="display-cards-info">
              <div class="col-md-6 d-flex align-items-center justify-content-center">
                <div class="d-flex justify-content-between">
                  <div class="display-cards-pic-back">
                    <%= image_tag "objects/#{object.image_path}" %>
                  </div>
                  <div class="vertical-line"></div>
                  <div style="width: 50%;">
                    <p style="text-align: center; font-size: 14px;">Average Distance to Earth:
                    <p>
                    <strong style="font-size:18px; font-family: AKONY;">~0.38</strong>
                    </p>
                    <p>/mm km</p>
                  </div>
                </div>
              </div>
              <div class="horizontal-line"></div>
              <div class="object-content">
                <p style="text-align: left; font: bold;">Funfact</p>
                <p style="text-align: left;"><%= object.funfact %></p>
                <div class="horizontal-line"></div>
                <p style="text-align: left;">Description</p>
                <p style="text-align: left;"><%= object.summary %></p>
              </div>
              <div class="horizontal-line"></div>
              <div class="display-cards-buttons d-flex justify-content-between">
                <div>
                  <button class="btn flip-button" data-controller="flipcard" data-action="click->flipcard#flip">
                    <i class="fas fa-sync-alt"></i> Flip card
                  </button>
                </div>
                <div>
                  <%= simple_form_for(@card, url: usergallery_usergallerycards_path(@usergallery), method: 'POST') do |f| %>
                    <%= f.input :id, as: :hidden %>
                    <%= f.submit "+ Add to gallery", class: 'mb-3 btn' %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/usercards/detail.html.erb
<div class="display-cards-bg">
  <%= render "shared/newnavbar" %>
  <div class="container">
    <%= render "shared/logo" %>

    <div class="flip-container">
      <div class="flipper">
        <% card = Card.find(@card.card_id) %>
        <% object = card.object %>
        <!-- Card front -->
        <div class="flip-dcard-front">
          <div class="display-cards-card container">
            <div class="row">
              <div class="col-md-6 d-flex align-items-center justify-content-center" style="padding: 20px">
                <p style="font-size: 18px; font-family: AKONY;"><%= object.name_en %></p>
              </div>
              <div class="col-md-6 d-flex align-items-center justify-content-center">
                <div class="d-flex flex-column align-items-center justify-content-center">
                  <div class="display-cards-pic" style="margin: -20px;">
                    <%= image_tag "objects/#{object.image_path}" %>
                  </div>
                  <div class="display-cards-info">
                    <div class="horizontal-line"></div>
                    <div class="object-front-content">

                      <div class="d-flex justify-content-between">
                        <div class="content-front">
                          <div class="cf-title">Diameter</div>
                          <div class="cf-content"><%="#{object.diameter} km" %></div>
                          <div class="cf-title">Gravity</div>
                          <div class="cf-content"><%="#{object.gravity} m/s²" %></div>
                        </div>

                        <div class="vertical-line"></div>

                        <div class="content-front">
                          <div class="cf-title">Temperature min</div>
                          <div class="cf-content"><%="#{object.temp_min} °C" %></div>
                          <div class="cf-title">Temperature max</div>
                          <div class="cf-content"><%="#{object.temp_max} °C" %></div>

                        </div>

                      </div>
                      <div class="horizontal-line"></div>
                      <p style="text-align: left; font-size: 14px;">Type
                        <span class="ps-1"><strong style="font-size:18px; font: bold;"><%= object.classification.capitalize %></strong></span>
                      </p>
                      <% if card.object_type == 'Star' %>
                        <p style="text-align: left; font-size: 14px;">Distance to earth
                          <span class="ps-1"><strong style="font-size: 18px; font: bold;"><%= object.distance_to_earth %></strong></span>
                        </p>
                        <p style="text-align: left; font-size: 14px;">Number of planets
                          <span class="ps-1"><strong style="font-size: 18px; font: bold;"><%= object.planets.count %></strong></span>
                        </p>
                      <% elsif card.object_type == 'Planet' %>
                        <p style="text-align: left; font-size: 14px;">Distance to sun
                          <span class="ps-1"><strong style="font-size: 18px; font: bold;"><%= object.distance_from_star %></strong></span>
                        </p>
                        <p style="text-align: left; font-size: 14px;">Main moons:
                          <span class="ps-1"><strong style="font-size: 18px; font: bold;"><%= object.main_moon %></strong></span>
                        </p>
                      <% elsif card.object_type == 'Satellite' %>
                        <p style="text-align: left; font-size: 14px;">Planet:
                          <span class="ps-1"><strong style="font-size: 18px; font: bold;"><%= object.planet.name_en.capitalize %></strong></span>
                        </p>
                        <p style="text-align: left; font-size: 14px;">Distance to planet
                          <span class="ps-1"><strong style="font-size: 18px; font: bold;"><%= object.distance_from_planet %></strong></span>
                        </p>
                      <% end %>
                      <p style="text-align: left; font-size: 14px;">Estimated distance to earth
                          <span class="ps-1"><strong style="font-size: 18px; font: bold;"><%="#{object.average_distance_to_earth} million km"%></strong></span>
                        </p>
                    </div>
                    <div class="horizontal-line"></div>
                    <div class="display-cards-buttons">
                      <div>
                        <button class="btn flip-card-button">
                          <i class="fas fa-sync-alt"></i> Flip card
                        </button>
                      </div>
                      <div>
                        <%= simple_form_for(@card, url: usergallery_usergallerycards_path(@usergallery), method: 'POST') do |f| %>
                          <%= f.input :id, as: :hidden %>
                          <%= f.button :submit, "+ Add to gallery", class: 'btn mb-3' %>
                        <% end %>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        <!-- Card back -->
        <div class="flip-dcard-back">
          <div class="display-cards-card container">
            <div class="row">
              <div class="display-cards-info">
                <div>
                  <div class="display-detailcards-pic-back">
                    <%= image_tag "objects/#{object.image_path}" %>
                  </div>
                  <div class="d-flex justify-content-between">
                    <div style="width: 50%;">
                      <p style="text-align: center; font: bold; margin-bottom:5px;">Rotation</p>
                      <p style="margin-bottom:5px;">
                        <strong style="text-align: center; font-family: AKONY;"><%= object.rotation %></strong></p>
                      <span style="text-align: center">(earth day)</span>
                    </div>
                    <div style="width: 50%">
                      <p style="text-align: center; font: bold; margin-bottom:5px;">Revolution</p>
                      <p style="margin-bottom:5px;">
                        <strong style="text-align: center; font-family: AKONY;"><%= object.revolution %></strong></p>
                      <span style="text-align: center">(earth year)</span>
                    </div>
                  </div>
                </div>
                <div class="horizontal-line"></div>
                <div class="object-content">
                    <p style="text-align: left; font: bold;">Funfact</p>
                    <p style="text-align: left;"><%= object.funfact %></p>
                  <div class="horizontal-line"></div>
                  <p style="text-align: left; font: bold;">Description</p>
                  <p style="text-align: left;"><%= object.summary %></p>
                </div>
                <div class="horizontal-line"></div>
                <div class="display-cards-buttons d-flex justify-content-between">
                  <button class="btn flip-card-button">
                    <i class="fas fa-sync-alt"></i> Flip card
                  </button>
                  <%= simple_form_for(@card, url: usergallery_usergallerycards_path(@usergallery), method: 'POST') do |f| %>
                    <%= f.input :id, as: :hidden %>
                    <%= f.submit "+ Add to gallery", class: 'mb-3 btn' %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
// Trigger flip effect when the flip-card-button is clicked
document.querySelectorAll('.flip-card-button').forEach(function(button) {
  button.addEventListener('click', function() {
    // Find the parent flip-container
    var flipContainer = this.closest('.flip-container');
    // Toggle the .flipped class
    flipContainer.querySelector('.flipper').classList.toggle('flipped');
  });
});

// Trigger flip effect when clicking on the flip-card-back
  // document.querySelectorAll('.flip-dcard-back').forEach(function(back) {
  //   back.addEventListener('click', function() {
  //     // Find the parent flip-container
  //     var flipContainer = this.closest('.flip-container');
  //     console.log("flipped")
  //     // If the flipper is flipped (back side is showing), flip it back to the front
  //     if (flipContainer.querySelector('.flipper').classList.contains('flipped')) {
  //       flipContainer.querySelector('.flipper').classList.remove('flipped');
  //     }
  //   });
  // });

  // Prevent flip effect when hovering over the flip-container
  document.querySelectorAll('.flip-container').forEach(function(container) {
    container.addEventListener('mouseenter', function() {
      if (!this.querySelector('.flipper').classList.contains('flipped')) {
        this.classList.add('hover');
      }
    });

    container.addEventListener('mouseleave', function() {
      if (!this.querySelector('.flipper').classList.contains('flipped')) {
        this.classList.remove('hover');
      }
    });
  });

</script>

app/views/usercards/index.html.erb
<div class="collection-bg">
  <%= render "shared/newnavbar" %>
  <div class="container collection">
    <%= render "shared/logo" %>
    <div class="collection-summary">
      <div class="collection-summary-block">
        <div class="summary-title">
          Total Cards
        </div>
        <div class="content">
          <% nbusercard = Usercard.where(user: current_user).count %>
          <%= nbusercard %>
        </div>
      </div>
      <div class="collection-summary-block">
        <div class="summary-title border-left">
            Missed Cards
        </div>
        <div class="content border-left">
          <%= @missingcards.count %>
        </div>
      </div>
    </div>
    <div class="collection-listing">
      <p class="section-title">My Collection</p>
      <div class="listing-cards">
        <% @usercards.each do |usercard| %>
          <% card = Card.find(usercard.card_id) %>
          <% object = card.object %>
          <% if card.object_type == 'Special' %>
            <%# bonus card %>
            <%= link_to usercards_bonus_path(usercard.id) do %>
              <div class="l-card special-border">
                <%= image_tag "objects/#{object.image_path}" %>

                <div class="l-card-content">
                <div class="title">
                  <div><strong><%= object.name_en.capitalize %></strong></div>
                  <div><%= card.object_type %></div>
                </div>
                <div class="infos">
                  <span class="funfact" data-controller="truncate" data-truncate-target="fun"><%= object.funfact %></span>

                </div>

              </div>
              </div>
            <% end %>
          <% else %>
            <%# regular card %>
            <%= link_to usercards_detail_path(usercard.id) do %>
              <div class="l-card">
                <%= image_tag "objects/#{object.image_path}" %>
                <div class="l-card-content">
                <div class="title">
                  <div><strong><%= object.name_en.capitalize %></strong></div>
                  <div><%= card.object_type %></div>
                </div>
                <div class="infos">
                  <span class="funfact" data-controller="truncate" data-truncate-target="fun"><%= object.funfact %></span>
                </div>

              </div>
              </div>
            <% end %>
          <% end %>

        <% end %>
      </div>
      </div>
      <% if @missingcards.count != 0 %>
        <div class="collection-missing">
          <p class="section-title">Unknown cards</p>
          <div class="missing-cards">
            <% @missingcards.each do |missing| %>
              <% object = missing.object %>
              <div class="m-card">
                <div>
                  <%= image_tag asset_path('objects/unknow card.png') %>
                </div>
                <div class="subtitle-missing">
                  <%= object.name_en %>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>